config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get '/admin' => 'admin/homes#top', as: 'admin'
  get '/about' => 'public/homes#about', as: 'about'
  get "/search" => "public/items#search"

  get '/customers' => 'public/customers#show'
  get '/customers/information/edit' => 'public/customers#edit'
  patch '/customers/information/' => 'public/customers#update'
  get '/customers/confirm' => 'public/customers#confirm'
  patch '/customers' => 'public/customers#unsubscribe', as: 'customers_unsubscribe'

  delete '/cart_items' => 'public/cart_items#destroy_all'

  post '/orders/confirm' => 'public/orders#confirm'
  get '/orders/finished' => 'public/orders#finished'

  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]
  end

  namespace :admin do
    resources :homes, only: [:top]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  with_options presence: true do
    validates :image
    validates :name
    validates :introduction
    validates :genre_id
    validates :price
    validates :is_active
  end

  enum is_active: { on_sale: true, stop_sell: false }



  def get_image(width, height)
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price
    (self.price * 1.10).round
  end

  def self.search(keyword)
    where(["name like?", "%#{keyword}%"])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @genres = Genre.all
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "新しい商品を登録しました！"
      redirect_to admin_item_path(@item)
    else
      @genres = Genre.all
      flash[:danger] = "未入力の項目があります！"
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "商品情報を変更しました！"
      redirect_to admin_item_path(@item)
    else
      @genres = Genre.all
      flash[:danger] = "未入力の項目があります！"
      render :edit
    end
  end


  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<%= render 'layouts/alert' %>

<div class="container py-5">
  <h5 class="mb-5">
    <span class="bg-dark text-white py-2 px-5 font-weight-bold">
      商品編集
    </span>
  </h5>

  <div class="w-75 mx-auto my-5">
    <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>

      <div class="form-group row">
        <%= f.label :"商品画像", class: "col-md-3 col-form-label" %>
        <div class="col-md-8">
          <%= f.file_field :image, accept: "image/*", class: "py-1 form-control-file", id: "image_file" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"商品名", class: "col-md-3 col-form-label", for: "item_name" %>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", id: "item_name", placeholder:"商品名" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"商品説明", class: "col-md-3 col-form-label", for: "item_introduction" %>
        <div class="col-md-8">
          <%= f.text_area :introduction, class: "form-control", id: "item_introduction", rows:"6", placeholder:"ここに説明文を記述します" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"ジャンル", class: "col-md-3", for: "item_genre" %>
        <div class="col-md-8">
          <%= f.select :genre_id, @genres.map{ |genre| [genre.name, genre.id] },{}, { id: "item_genre", class: "form-control" } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"販売価格", class: "col-md-3", for: "item_price" %>
        <div class="col-md-8">
          <%= f.number_field :price, class: "form-control", id: "item_price", placeholder:"1000" %>
        </div>
        <div class="col-md-1 px-0 pt-2">
          円
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"販売ステータス", class: "col-md-3 col-form-label" %>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, :on_sale, id: "item_on_sale" %>
          <%= f.label :"販売中", class: "form-check-label px-2", for: "item_on_sale" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, :stop_sell, id: "item_stop_sell" %>
          <%= f.label :"販売停止中", class: "form-check-label px-2", for: "item_stop_sell" %>
        </div>
      </div>

      <div class="actions pt-3">
        <%= f.submit '変更を保存', class:"btn btn-light bg-gold btn-block" %>
      </div>
    <% end %>
  </div>

</div>

app/views/admin/items/index.html.erb
<div class="container py-5">
  <h5 class="mb-5">
    <span class="bg-dark text-white py-2 px-5 font-weight-bold">
      商品一覧
    </span>
  </h5>

  <p class="w-50 ml-auto">
    <%= link_to "新しい商品を登録する", new_admin_item_path, class: "btn btn-light bg-gold btn-block" %>
  </p>

  <table class="table table-bordered my-4">
    <thead class="text-center table-active">
      <tr>
        <th>商品ID</th>
        <th class="w-50">商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td class="text-center">
          <%= item.id %>
        </td>
        <td class="px-4">
          <%= link_to admin_item_path(item), class:"text-danger" do%>
            <%= item.name %>
          <% end %>
        </td>
        <td class="text-right">
          <%= item.price.to_s(:delimited) %>
        </td>
        <td class="text-center">
          <%= item.genre.name %>
        </td>
        <td class="text-center font-weight-bold">
          <% if item.is_active == "on_sale" %>
            <span class="text-success"><%= item.is_active_i18n %></span>
          <% else %>
            <span class="text-black-50"><%= item.is_active_i18n %></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row justify-content-center pt-3">
    <%= paginate @items %>
  </div>

</div>

app/views/admin/items/new.html.erb
<%= render 'layouts/alert' %>

<div class="container py-5">
  <h5 class="mb-5">
    <span class="bg-dark text-white py-2 px-5 font-weight-bold">
      商品新規登録
    </span>
  </h5>

  <div class="w-75 mx-auto my-5">
    <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

      <div class="form-group row">
        <%= f.label :"商品画像", class: "col-md-3 col-form-label" %>
        <div class="col-md-8">
          <%= f.file_field :image, accept: "image/*", class: "py-1 form-control-file", id: "image_file" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"商品名", class: "col-md-3 col-form-label", for: "item_name" %>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", id: "item_name", placeholder:"商品名" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"商品説明", class: "col-md-3 col-form-label", for: "item_introduction" %>
        <div class="col-md-8">
          <%= f.text_area :introduction, class: "form-control", id: "item_introduction", rows:"6", placeholder:"ここに説明文を記述します" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"ジャンル", class: "col-md-3", for: "item_genre" %>
        <div class="col-md-8">
          <%= f.select :genre_id, @genres.map{ |genre| [genre.name, genre.id] },{ include_blank: "--選択してください--" }, { id: "item_genre", class: "form-control" } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"販売価格", class: "col-md-3", for: "item_price" %>
        <div class="col-md-8">
          <%= f.number_field :price, class: "form-control", id: "item_price", placeholder:"1000" %>
        </div>
        <div class="col-md-1 px-0 pt-2">
          円
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :"販売ステータス", class: "col-md-3 col-form-label" %>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, Item.is_actives.key(true), id: "item_on_sale" %>
          <%= f.label :is_active, Item.is_actives_i18n[:on_sale], class: "form-check-label px-2", for: "item_on_sale"  %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, Item.is_actives.key(false), id: "item_stop_sell"  %>
          <%= f.label :is_active, Item.is_actives_i18n[:stop_sell], class: "form-check-label px-2", for: "item_stop_sell" %>
        </div>
      </div>

      <div class="actions pt-3">
        <%= f.submit '新規登録', class:"btn btn-light bg-gold btn-block" %>
      </div>
    <% end %>
  </div>

</div>

app/views/admin/items/show.html.erb
<%= render 'layouts/alert' %>

<div class="container py-5">
  <h5 class="mb-5">
    <span class="bg-dark text-white py-2 px-5 font-weight-bold">
      商品詳細
    </span>
  </h5>

  <div class="row justify-content-center py-5">

    <div class="col-lg-4 pb-3">
      <%= image_tag @item.get_image(350,245), class: "img-thumbnail mx-auto d-block" %>
    </div>

    <div class="col-lg-7">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品名</th>
            <td class="w-75"><%= @item.name %></td>
          </tr>
          <tr>
            <th>商品説明</th>
            <td class="w-75"><%= @item.introduction %></td>
          </tr>
          <tr>
            <th>ジャンル</th>
            <td class="w-75"><%= @item.genre.name %></td>
          </tr>
          <tr>
            <th>税込価格<br>
            <span class="small">(税抜価格)</span></th>
            <td class="w-75"><%= @item.add_tax_price.to_s(:delimited) %> ( <%= @item.price.to_s(:delimited) %> ) 円</td>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <td class="w-75 font-weight-bold">
              <% if @item.is_active == "on_sale" %>
                <span class="text-success"><%= @item.is_active_i18n %></span>
              <% else %>
                <span class="text-black-50"><%= @item.is_active_i18n %></span>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-light bg-gold btn-block" %>
    </div>

  </div>
</div>