config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get '/admin' => 'admin/homes#top', as: 'admin'
  get '/about' => 'public/homes#about', as: 'about'
  get "/search" => "public/items#search"

  get '/customers' => 'public/customers#show'
  get '/customers/information/edit' => 'public/customers#edit'
  patch '/customers/information/' => 'public/customers#update'
  get '/customers/confirm' => 'public/customers#confirm'
  patch '/customers' => 'public/customers#unsubscribe', as: 'customers_unsubscribe'

  delete '/cart_items' => 'public/cart_items#destroy_all'

  post '/orders/confirm' => 'public/orders#confirm'
  get '/orders/finished' => 'public/orders#finished'

  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]
  end

  namespace :admin do
    resources :homes, only: [:top]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  with_options presence: true do
    validates :postal_code
    validates :address
    validates :name
    validates :postage
    validates :payment_price
    validates :payment_method
  end


  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { wait_payment: 0, confirm_payment: 1, making: 2, shipping_prepare: 3, shipping_finish: 4 }



  def items_total
    total = 0
    self.order_details.each do |order_detail|
      order_detail.subtotal
      total += order_detail.subtotal
    end
    return total
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    if params[:order][:order_status] == "confirm_payment"
      @order.update(order_params)
        @order.order_details.each do |order_detail|
          order_detail.update(making_status: 1)
        end
      flash[:warning] = "入金を確認しました！製作を開始してください！"
      redirect_to admin_order_path(@order)
    elsif params[:order][:order_status] == "shipping_finish" && @order.order_details.count == @order.order_details.where(making_status: "making_finish").count
      @order.update(order_params)
      flash[:success] = "発送しました！お疲れ様でした！"
      redirect_to admin_order_path(@order)
    else
      flash[:danger] = "操作できません！製作ステータスを確認してください！"
      render :show
    end
  end



  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<%= render 'layouts/alert' %>

<div class="container py-5">
  <h5 class="mb-5">
    <span class="bg-dark text-white py-2 px-5 font-weight-bold">
      注文履歴詳細
    </span>
  </h5>

  <div class="row justify-content-center">
    <div class="col-md-7">
      <table class="table">
        <tbody>
          <tr>
            <th>購入者</th>
            <td>
              <%= link_to admin_customer_path(@order), class:"text-dark" do%>
                <%= @order.customer.first_name %><%= @order.customer.last_name %>
              <% end %>
            </td>
            <td class="w-25"></td>
          </tr>
          <tr>
            <th>注文日</th>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
            <td></td>
          </tr>
          <tr>
            <th>配送先</th>
            <td colspan="2">
              〒<%= @order.postal_code %> <%= @order.address %><br>
              <%= @order.name %>
            </td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method_i18n %></td>
            <td></td>
          </tr>
          <tr>
            <th>注文ステータス</th>
            <td class="py-2">
              <%= form_with model: @order, url: admin_order_path(@order), method: :patch, class: "form-inline" do |f| %>
                <div class="form-group">
                  <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]}, {}, { class: "form-control" } %>
                </div>
                <%= f.submit '更新', class:"btn btn-light bg-gold" %>
              <% end %>
            </td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-borderless table-active rounded-lg">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td class="text-right"><%= @order.items_total.to_s(:delimited) %> 円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td class="text-right"><%= @order.postage %> 円</td>
          </tr>
          <tr class="h4 font-weight-bolder">
            <th>請求金額合計</th>
            <td class="text-right"><%= @order.payment_price.to_s(:delimited) %> 円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="my-3 mx-5">
    <table class="table table-bordered">
      <thead class="text-center table-active">
        <tr>
          <th class="w-50">商品名</th>
          <th>単価 <small>(税込)</small></th>
          <th>数量</th>
          <th>小計</th>
          <th class="px-0">製作ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @order.order_details.each do |order_detail| %>
          <tr>
            <td>
              <%= order_detail.item.name %>
            </td>
            <td class="text-right">
              <%= order_detail.price %>
            </td>
            <td class="text-right">
              <%= order_detail.amount %>
            </td>
            <td class="text-right">
              <%= order_detail.subtotal.to_s(:delimited) %>
            </td>
            <td class="align-middle py-0">
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, class: "justify-content-center form-inline" do |f| %>
                <div class="form-group">
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]}, {}, { class: "form-control" } %>
                  <%= f.hidden_field :order_detail_id, value: order_detail.id %>
                </div>
                <%= f.submit '更新', class:"btn btn-light bg-gold" %>
              <% end %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>

</div>