config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get '/admin' => 'admin/homes#top', as: 'admin'
  get '/about' => 'public/homes#about', as: 'about'
  get "/search" => "public/items#search"

  get '/customers' => 'public/customers#show'
  get '/customers/information/edit' => 'public/customers#edit'
  patch '/customers/information/' => 'public/customers#update'
  get '/customers/confirm' => 'public/customers#confirm'
  patch '/customers' => 'public/customers#unsubscribe', as: 'customers_unsubscribe'

  delete '/cart_items' => 'public/cart_items#destroy_all'

  post '/orders/confirm' => 'public/orders#confirm'
  get '/orders/finished' => 'public/orders#finished'

  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]
  end

  namespace :admin do
    resources :homes, only: [:top]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "新しいジャンルを追加しました！"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash[:danger] = "ジャンル名を入力してください！"
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:success] = "ジャンル名を変更しました！"
      redirect_to admin_genres_path
    else
      flash[:danger] = "ジャンル名を入力してください！"
      render :edit
    end
  end

private


  def genre_params
    params.require(:genre).permit(:name)
  end



end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<%= render 'layouts/alert' %>

<div class="container py-5">
  <h5 class="mb-5">
    <span class="bg-dark text-white py-2 px-5 font-weight-bold">
      ジャンル編集
    </span>
  </h5>

  <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
    <div class="form-group row justify-content-center py-5">
      <div class="col-md-2 text-center">
        <%= f.label :"ジャンル名", class: "col-form-label", for: "genre_name" %>
      </div>

      <div class="col-md-6">
        <%= f.text_field :name, class: "form-control", placeholder: "ジャンル名", id: "genre_name" %>
      </div>

      <div class="col-md-2">
        <%= f.submit "変更を保存", class: "btn btn-light bg-gold btn-block" %>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/genres/index.html.erb
<%= render 'layouts/alert' %>

<div class="container py-5">
  <h5 class="mb-5">
    <span class="bg-dark text-white py-2 px-5 font-weight-bold">
      ジャンル一覧・追加
    </span>
  </h5>

  <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
    <div class="row form-group justify-content-center py-5">
      <div class="col-md-2 text-center">
        <%= f.label :"ジャンル名", class: "col-form-label", for: "genre_name" %>
      </div>

      <div class="col-md-6">
        <%= f.text_field :name, class: "form-control", placeholder: "ジャンル名", id: "genre_name" %>
      </div>

      <div class="col-md-2">
        <%= f.submit "新規登録", class: "btn btn-light bg-gold btn-block" %>
      </div>
    </div>
  <% end %>

  <table class="table table-bordered mx-auto w-50">
    <thead class="table bg-dark text-white">
      <tr>
        <th class="px-4">ジャンル</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @genres.each do |genre| %>
      <tr>
        <td class="px-4">
          <%= genre.name %>
        </td>
        <td class="text-center table-active">
          <%= link_to "編集する", edit_admin_genre_path(genre), class: "text-dark" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>