config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get '/admin' => 'admin/homes#top', as: 'admin'
  get '/about' => 'public/homes#about', as: 'about'
  get "/search" => "public/items#search"

  get '/customers' => 'public/customers#show'
  get '/customers/information/edit' => 'public/customers#edit'
  patch '/customers/information/' => 'public/customers#update'
  get '/customers/confirm' => 'public/customers#confirm'
  patch '/customers' => 'public/customers#unsubscribe', as: 'customers_unsubscribe'

  delete '/cart_items' => 'public/cart_items#destroy_all'

  post '/orders/confirm' => 'public/orders#confirm'
  get '/orders/finished' => 'public/orders#finished'

  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]
  end

  namespace :admin do
    resources :homes, only: [:top]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  with_options presence: true do
    validates :postal_code
    validates :name
    validates :address
  end

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  with_options presence: true do
    validates :amount
  end




  def subtotal
    item.add_tax_price * amount
  end

  def self.items_total(cart_items)
    total = 0
    cart_items.each do |cart_item|
      cart_item.subtotal
      total += cart_item.subtotal
    end
    return total
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :first_name
    validates :last_name
    validates :first_name_kana
    validates :last_name_kana
    validates :postal_code
    validates :address
    validates :telephone_number
    validates :email
  end

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  enum is_deleted: { unsubscribe: true, membership: false }

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  with_options presence: true do
    validates :image
    validates :name
    validates :introduction
    validates :genre_id
    validates :price
    validates :is_active
  end

  enum is_active: { on_sale: true, stop_sell: false }



  def get_image(width, height)
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price
    (self.price * 1.10).round
  end

  def self.search(keyword)
    where(["name like?", "%#{keyword}%"])
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  with_options presence: true do
    validates :postal_code
    validates :address
    validates :name
    validates :postage
    validates :payment_price
    validates :payment_method
  end


  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { wait_payment: 0, confirm_payment: 1, making: 2, shipping_prepare: 3, shipping_finish: 4 }



  def items_total
    total = 0
    self.order_details.each do |order_detail|
      order_detail.subtotal
      total += order_detail.subtotal
    end
    return total
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  with_options presence: true do
    validates :price
    validates :amount
  end

  enum making_status: { cannot_start: 0, waiting_making: 1, making: 2, making_finish: 3 }
  
  
  
  def subtotal
    item.add_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "新しいジャンルを追加しました！"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash[:danger] = "ジャンル名を入力してください！"
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:success] = "ジャンル名を変更しました！"
      redirect_to admin_genres_path
    else
      flash[:danger] = "ジャンル名を入力してください！"
      render :edit
    end
  end

private


  def genre_params
    params.require(:genre).permit(:name)
  end



end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
    @total_amounts = 0
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @genres = Genre.all
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "新しい商品を登録しました！"
      redirect_to admin_item_path(@item)
    else
      @genres = Genre.all
      flash[:danger] = "未入力の項目があります！"
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "商品情報を変更しました！"
      redirect_to admin_item_path(@item)
    else
      @genres = Genre.all
      flash[:danger] = "未入力の項目があります！"
      render :edit
    end
  end


  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_alert.html.erb
<% flash.each do |message_type, message| %>
  <div class="container my-0 alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのCAKE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/148c06dab2.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Zen+Antique&display=swap" rel="stylesheet">
  </head>

  <body class="d-flex flex-column">
    <header class="border-bottom">
      <div class="container mt-2">
        <div class="row">

          <div class="col-8 col-md-5 pb-2">
            <%= link_to root_path do%>
              <%= image_tag('cake-logo.jpg') %>
            <% end %>
          </div>

          <div class="col-4 col-md-7">
            <div class="row">
              <nav class="navbar navbar-expand-md navbar-light ml-auto px-0">
                <button class="navbar-toggler ml-auto mt-2" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <% if customer_signed_in? %>
                  <span class="ml-auto mt-2">ようこそ、<%= current_customer.first_name %>さん！</span>
                <% end %>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav text-center">

                    <% if customer_signed_in? %>
                      <li class="nav-item pl-3">
                        <%= link_to customers_path, class: "nav-link btn-light border-right border-left" do%>
                          <i class="fa-solid fa-user"></i> Mypage
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to items_path, class: "nav-link btn-light border-right border-left" do %>
                          <i class="fa-solid fa-cake-candles"></i> Lineup
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to cart_items_path, class: "nav-link btn-light border-right border-left" do%>
                          <i class="fa-solid fa-cart-shopping"></i> Cart
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link btn-light border-right border-left" do%>
                          <i class="fas fa-sign-out-alt"></i> Log out
                        <% end %>
                      </li>

                    <% elsif admin_signed_in? %>
                      <li class="nav-item pl-3">
                        <%= link_to admin_items_path, class: "nav-link btn-light border-right border-left" do %>
                          商品一覧
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to admin_customers_path, class: "nav-link btn-light border-right border-left" do %>
                          会員一覧
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to admin_path, class: "nav-link btn-light border-right border-left" do %>
                          注文履歴一覧
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to admin_genres_path, class: "nav-link btn-light border-right border-left" do %>
                          ジャンル一覧
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link btn-light border-right border-left" do%>
                          ログアウト
                        <% end %>
                      </li>

                    <% else %>
                      <li class="nav-item pl-3">
                        <%= link_to about_path, class: "nav-link btn-light border-right border-left" do %>
                          <i class="fa-solid fa-circle-question"></i> About
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to items_path, class: "nav-link btn-light border-right border-left" do %>
                          <i class="fa-solid fa-cake-candles"></i> Lineup
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to new_customer_registration_path, class: "nav-link btn-light border-right border-left" do %>
                          <i class="fas fa-user-plus"></i> Sign up
                        <% end %>
                      </li>
                      <li class="nav-item pl-3">
                        <%= link_to new_customer_session_path, class: "nav-link btn-light border-right border-left" do %>
                          <i class="fa-solid fa-right-to-bracket"></i> Log in
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </nav>
            </div>

            <div class="row justify-content-end pt-2 pb-3">
              <%= form_with url: search_path, method: :get, class: "d-flex" do |f| %>
                <%= f.text_field :keyword, value: @keyword, class:"search form-control bg-gold w-100", placeholder: "search" %>
                <%= button_tag sanitize('<i class="fa fa-search"></i>'), :type => "submit", :class =>"btn btn-dark flex-shrink-1" %>
              <% end %>
            </div>
          </div>

        </div>
      </div>
    </header>

    <main class="h-100">
      <%= yield %>
    </main>

    <footer class="bg-dark_red flex-shrink-1">
      <div class="container text-white text-center p-4">
        <p class="m-0 p-3">CopyRight Infratop.inc</p>
      </div>
    </footer>

  </body>
</html>